INSERT INTO toppings (topping_category_id, name)
VALUES (1, 'Mozzarella'),
(1, 'Cheddar'),
(1, 'Feta'),
(2, 'Pepperoni'),
(2, 'Bacon'),
(2, 'Ham'),
(2, 'Chicken'),
(2, 'Italian Sausage'),
(3, 'Green Pepper'),
(3, 'Banana Peppers'),
(3, 'Mushrooms'),
(3, 'Black Olives'),
(3, 'Red Onion'),
(3, 'Pineapple'),
(3, 'Tomato');